### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by jaimevillegas** [BahirHakimy/ToDo-List#11]
Hi there! Awesome project! We only suggest the following:

- Kindly add some comments to your code explaining each part of it. It would be more documented.
- You can follow AAA pattern in some sections of your code. For example, defining constants before the functions would be easier to read and it will stick to best practices.

**Comment by BahirHakimy** [comment]
> Hi @jaimevillegas, Thank you very much for the suggestions, but are we in the same morning session group?

**Comment by jaimevillegas** [comment]
Hello @BahirHakimy. @yosaddis ask us to leave the issue in this repository

**Comment by BahirHakimy** [comment]
> Hello @BahirHakimy. @yosaddis ask us to leave the issue in this repository

Oh, Okay
